language: python

env:
- DB=pgsql
- DB=mysql
- DB=sqlite

services:
- postgresql
- mysql

python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7

install:
- pip install -U setuptools tox tox-travis

before_script:
- ./travis-ci.sh

script: tox

deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: adamhadani
  password:
    secure: jSAo1pMtzpNSBJHOtn15WiT2XBL6JBTB/1u22CeRhW6tmRh4ngaK1+WAfuoRpgP5seTBnb1DIxiNzvCL5sRjq9ckbHgc7pW9EcpKCeDFjU1MQPH2GqQ37jicc4NY4TXu9pAUIbxIVwGxHWNCY0QPxIgCSVvTTKoiZn3QddL8hzg=
  on:
    tags: true
    repo: RDFLib/rdflib-sqlalchemy
    branch: develop
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
